In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from scipy import stats

In [ ]:
#uploading datasets
diabetes=pd.read_csv('/content/Dataset of Diabetes .csv');
adult=pd.read_csv('/content/adult.csv');

In [ ]:
print(diabetes.head());

    ID  No_Pation Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0  502      17975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5
1  735      34221      M   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6
2  420      47975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5
3  680      87656      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5
4  504      34223      M   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4

    BMI CLASS
0  24.0     N
1  23.0     N
2  24.0     N
3  24.0     N
4  21.0     N

In [ ]:
print(diabetes.info());

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   object
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB
None

In [ ]:
print(diabetes.describe());

                ID     No_Pation          AGE         Urea           Cr  \
count  1000.000000  1.000000e+03  1000.000000  1000.000000  1000.000000
mean    340.500000  2.705514e+05    53.528000     5.124743    68.943000
std     240.397673  3.380758e+06     8.799241     2.935165    59.984747
min       1.000000  1.230000e+02    20.000000     0.500000     6.000000
25%     125.750000  2.406375e+04    51.000000     3.700000    48.000000
50%     300.500000  3.439550e+04    55.000000     4.600000    60.000000
75%     550.250000  4.538425e+04    59.000000     5.700000    73.000000
max     800.000000  7.543566e+07    79.000000    38.900000   800.000000

             HbA1c         Chol           TG          HDL          LDL  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean      8.281160     4.862820     2.349610     1.204750     2.609790
std       2.534003     1.301738     1.401176     0.660414     1.115102
min       0.900000     0.000000     0.300000     0.200000     0.300000
25%       6.500000     4.000000     1.500000     0.900000     1.800000
50%       8.000000     4.800000     2.000000     1.100000     2.500000
75%      10.200000     5.600000     2.900000     1.300000     3.300000
max      16.000000    10.300000    13.800000     9.900000     9.900000

              VLDL          BMI
count  1000.000000  1000.000000
mean      1.854700    29.578020
std       3.663599     4.962388
min       0.100000    19.000000
25%       0.700000    26.000000
50%       0.900000    30.000000
75%       1.500000    33.000000
max      35.000000    47.750000

In [ ]:
#Handling Missing Values
missing_values = diabetes.isnull().sum()
print(missing_values[missing_values > 0])

Series([], dtype: int64)

In [ ]:
diabetes=diabetes.replace(to_replace='f',value='F',regex=True)

In [ ]:
#Categorical values
#Handling categorical data

from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

diabetes = diabetes.replace(to_replace='f', value='F', regex=True)

# Initialize OrdinalEncoder for Gender column (F -> 0, M -> 1)
ordinal_encoder = OrdinalEncoder(categories=[["F", "M"]])

# Fit and transform the Gender column to create a new column 'Gender_Encoded'
diabetes["Gender_Encoded"] = ordinal_encoder.fit_transform(diabetes[["Gender"]])

# Initialize OneHotEncoder for CLASS column
onehot_encoder = OneHotEncoder(sparse_output=False)  # sparse_output=False gives a dense matrix

# Fit and transform the CLASS column
encoded_data = onehot_encoder.fit_transform(diabetes[["CLASS"]])

# Convert the resulting numpy array to a DataFrame with appropriate column names
encoded_df = pd.DataFrame(encoded_data, columns=onehot_encoder.get_feature_names_out(["CLASS"]))

# Concatenate the encoded columns with the original DataFrame
diabetes_encoded = pd.concat([diabetes, encoded_df], axis=1)

# Drop the original categorical columns (Gender and CLASS) since we have encoded versions
diabetes_encoded.drop(["Gender", "CLASS"], axis=1, inplace=True)

# Display the first few rows of the updated DataFrame
print(diabetes_encoded.head())

    ID  No_Pation       AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI  \
0  502      17975 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
1  735      34221 -3.130017   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6  23.0
2  420      47975 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
3  680      87656 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
4  504      34223 -2.334096   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4  21.0

   Gender_Encoded  CLASS_N  CLASS_N   CLASS_P  CLASS_Y  CLASS_Y
0             0.0      1.0       0.0      0.0      0.0       0.0
1             1.0      1.0       0.0      0.0      0.0       0.0
2             0.0      1.0       0.0      0.0      0.0       0.0
3             0.0      1.0       0.0      0.0      0.0       0.0
4             1.0      1.0       0.0      0.0      0.0       0.0

In [ ]:
#Handling Outliers
def detect_outliers(data):
    outliers = []
    threshold = 3
    mean = np.mean(data)
    std = np.std(data)
    z_score=(data-mean)//std
    for i in range(len(data)):
        if np.abs(z_score[i])>threshold:
            outliers.append(i)
    return outliers

print("For Age Column:")
print(detect_outliers(diabetes['AGE']))

For Age Column:
[1, 86, 953, 979]

In [ ]:
#Data Transformation
#Min-Max Scalar for age column
normalizer = MinMaxScaler()
diabetes[['AGE']] = normalizer.fit_transform(diabetes[['AGE']])
diabetes.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,0.508475,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,0.101695,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,0.508475,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,0.508475,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,0.220339,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

In [ ]:
#Standard Scalar
normalizer = StandardScaler()
diabetes[['AGE']] = normalizer.fit_transform(diabetes[['AGE']])
diabetes.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,-0.401144,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,-3.130017,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,-0.401144,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,-0.401144,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,-2.334096,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

In [ ]:
# for adult dataset
print(adult.head());

   age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married
1   38    Private   89814       HS-grad                9  Married-civ-spouse
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse
3   44    Private  160323  Some-college               10  Married-civ-spouse
4   18          ?  103497  Some-college               10       Never-married

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0
1    Farming-fishing      Husband  White    Male             0             0
2    Protective-serv      Husband  White    Male             0             0
3  Machine-op-inspct      Husband  Black    Male          7688             0
4                  ?    Own-child  White  Female             0             0

   hours-per-week native-country income
0              40  United-States  <=50K
1              50  United-States  <=50K
2              40  United-States   >50K
3              40  United-States   >50K
4              30  United-States  <=50K

In [ ]:
print(adult.info());

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB
None

In [ ]:
print(adult.describe());

                age        fnlwgt  educational-num  capital-gain  \
count  48842.000000  4.884200e+04     48842.000000  48842.000000
mean      38.643585  1.896641e+05        10.078089   1079.067626
std       13.710510  1.056040e+05         2.570973   7452.019058
min       17.000000  1.228500e+04         1.000000      0.000000
25%       28.000000  1.175505e+05         9.000000      0.000000
50%       37.000000  1.781445e+05        10.000000      0.000000
75%       48.000000  2.376420e+05        12.000000      0.000000
max       90.000000  1.490400e+06        16.000000  99999.000000

       capital-loss  hours-per-week
count  48842.000000    48842.000000
mean      87.502314       40.422382
std      403.004552       12.391444
min        0.000000        1.000000
25%        0.000000       40.000000
50%        0.000000       40.000000
75%        0.000000       45.000000
max     4356.000000       99.000000

In [ ]:
#Handling Missing Values
missing_values = adult.isnull().sum()
print(missing_values[missing_values > 0])

Series([], dtype: int64)

In [ ]:
#Handling categorical data

from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

# Initialize OrdinalEncoder for Gender column
ordinal_encoder = OrdinalEncoder(categories=[["Male", "Female"]])

# Fit and transform the Gender column
adult["Gender_Encoded"] = ordinal_encoder.fit_transform(adult[["gender"]])

# Initialize OneHotEncoder for Workclass column
onehot_encoder = OneHotEncoder()

# Fit and transform the Workclass column
encoded_data = onehot_encoder.fit_transform(adult[["workclass"]])

# Convert the sparse matrix to a dense array
encoded_array = encoded_data.toarray()

# Convert to DataFrame for better visualization
encoded_df = pd.DataFrame(encoded_array, columns=onehot_encoder.get_feature_names_out(["workclass"]))

# Concatenate the encoded columns with the original DataFrame
income_encoded = pd.concat([adult, encoded_df], axis=1)

# Drop the original categorical columns (gender and workclass)
income_encoded.drop(["gender", "workclass"], axis=1, inplace=True)

# Display the first few rows of the updated DataFrame
print(income_encoded.head())

   age  fnlwgt     education  educational-num      marital-status  \
0   25  226802          11th                7       Never-married
1   38   89814       HS-grad                9  Married-civ-spouse
2   28  336951    Assoc-acdm               12  Married-civ-spouse
3   44  160323  Some-college               10  Married-civ-spouse
4   18  103497  Some-college               10       Never-married

          occupation relationship   race  capital-gain  capital-loss  ...  \
0  Machine-op-inspct    Own-child  Black             0             0  ...
1    Farming-fishing      Husband  White             0             0  ...
2    Protective-serv      Husband  White             0             0  ...
3  Machine-op-inspct      Husband  Black          7688             0  ...
4                  ?    Own-child  White             0             0  ...

   Gender_Encoded workclass_? workclass_Federal-gov  workclass_Local-gov  \
0             0.0         0.0                   0.0                  0.0
1             0.0         0.0                   0.0                  0.0
2             0.0         0.0                   0.0                  1.0
3             0.0         0.0                   0.0                  0.0
4             1.0         1.0                   0.0                  0.0

   workclass_Never-worked  workclass_Private  workclass_Self-emp-inc  \
0                     0.0                1.0                     0.0
1                     0.0                1.0                     0.0
2                     0.0                0.0                     0.0
3                     0.0                1.0                     0.0
4                     0.0                0.0                     0.0

   workclass_Self-emp-not-inc  workclass_State-gov  workclass_Without-pay
0                         0.0                  0.0                    0.0
1                         0.0                  0.0                    0.0
2                         0.0                  0.0                    0.0
3                         0.0                  0.0                    0.0
4                         0.0                  0.0                    0.0

[5 rows x 23 columns]

In [ ]:
#Handling Outliers
def detect_outliers(data):
    outliers = []
    threshold = 3
    mean = np.mean(data)
    std = np.std(data)
    z_score=(data-mean)//std
    for i in range(len(data)):
        if np.abs(z_score[i])>threshold:
            outliers.append(i)
    return outliers

print("For Age Column:")
print(detect_outliers(adult['age']))

For Age Column:
[]

In [ ]:
#Data Transformation
#Min-Max Scalar for age column
normalizer = MinMaxScaler()
adult[['age']] = normalizer.fit_transform(adult[['age']])
adult.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,0.109589,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,0.287671,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,0.150685,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,0.369863,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,0.013699,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [ ]:
#Standard Scalar
normalizer = StandardScaler()
adult[['age']] = normalizer.fit_transform(adult[['age']])
adult.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,-0.995129,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,-0.046942,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,-0.776316,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,0.390683,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,-1.505691,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K